plugins:
  dumbcourse_enabled:
    default: true
    client: true
  dumbcourse_default_theme:
    default: "dark"
    client: true
    type: enum
    choices:
      - dark
      - light
  dumbcourse_default_view:
    default: "latest"
    client: true
    type: enum
    choices:
      - latest
      - new
      - top
      - unseen
      - hot
      - my
      - categories
  dumbcourse_base_path:
    default: "dumb"
    client: true
  dumbcourse_sidebar_link_enabled:
    default: true
    client: true
  dumbcourse_show_category_names:
    default: true
    client: true
  dumbcourse_show_topic_posters:
    default: true
    client: true
  dumbcourse_show_topic_posters_mobile:
    default: true
    client: true
  dumbcourse_show_topic_posters_desktop:
    default: true
    client: true
  dumbcourse_push_enabled:
    default: true
    client: false
  dumbcourse_ntfy_server:
    default: "https://ntfy.sh"
    client: true
  dumbcourse_ntfy_token:
    default: ""
    secret: true
    client: false
  dumbcourse_pagination_enabled:
    default: false
    client: true
  dumbcourse_topics_per_page:
    default: 30
    min: 10
    max: 100
    client: true
